In [1]:
import numpy as np

In [2]:
numpy_array = np.arange(0, 1000000)
python_list = range(1000000)

In [5]:
print "python list"
time = %timeit -r 1 -o sum(python_list)
print time.all_runs[0]/time.loops 

python list
100 loops, best of 1: 8.79 ms per loop
0.0087925696373


In [4]:
print "\n" + "numpy array"
time = %timeit -r 1 -o np.sum(numpy_array)
print time.all_runs[0]/time.loops


numpy array
The slowest run took 4.14 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 1: 866 µs per loop
0.000866365909576


In [3]:
print "\n" + "numpy array -- standard library sum"
time = %timeit -r 1 -o sum(numpy_array)
print time.all_runs[0]/time.loops


numpy array -- standard library sum
10 loops, best of 1: 95.1 ms per loop
0.0951096057892


In [ ]:
#types

In [ ]:
my_lst_ndarray = np.array([1, 2, 3, 4, 5])
my_tuple_ndarray = np.array((1, 2, 3, 4, 5), np.int32)

In [ ]:
print my_lst_ndarray.shape
print my_tuple_ndarray.shape

In [ ]:
print my_lst_ndarray.dtype
print my_tuple_ndarray.dtype

In [ ]:
my_lst_ndarray2 = np.array(["1", 2, 3, "10", 5])
print my_lst_ndarray2.dtype

In [ ]:
my_lst_ndarray3 = np.array([1, 2, 3, "10", 5], np.int32) 
print my_lst_ndarray3.dtype

In [ ]:

# This will not work, because Python can't cast the string 'bozo' as a 32 bit integer. 
my_lst_ndarray3 = np.array([1, 2, 3, "ten", 5], np.int32) 

In [ ]:
# element-wise

In [9]:
[1, 2, 3] + [3, 2, 1]

[1, 2, 3, 3, 2, 1]

In [10]:
np.array([1, 2, 3]) + np.array([3, 2, 1])

array([4, 4, 4])

In [ ]:
first_arr = np.array([[1, 2], [3, 4]]) 
second_arr = np.array([[5, 6], [7, 8]]) 
first_arr * second_arr

In [ ]:
first_arr - np.array([4])

In [ ]:
first_arr * 5

In [ ]:
first_arr % 3

In [12]:
# broadcasting

In [24]:
a = np.array([[10], [-10]]) 
# a = np.array([[10,-10]]) 
b = np.array([[1, 2], [-1, -2]]) 

print a.shape, b.shape 
print "\n"
print a + b

# elements will "duplicate, expand, and fill up" 
# to make the dimensions compatible for element-wise operations
# cool.

(1, 2) (2, 2)


[[ 11  -8]
 [  9 -12]]


In [14]:
a = np.array([[10, 0, -10],[-10, 0, -10]]) 
b = np.array([[1,2],[-1,-2]]) 
print a.shape, b.shape 
print ""
print a + b

# it's not clear how it should fill up in this case... so it can't/doesn't

(2, 3) (2, 2)



ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [20]:
#a = 10
a = np.array(10)
a = np.array([10])
b = np.array([[1,2],[-1,-2]]) 

print a.shape, b.shape 
print "\n"
print a + b

(1,) (2, 2)


[[11 12]
 [ 9  8]]


In [ ]:
# matrix convenience functions

In [8]:
How could I create a numpy array holding the numbers 1 - 10?
How could I create a numpy array holding the numbers 10 - 20 ?
How would I create a numpy array of all zeros that has 10 rows and 20 columns?
How would I create a numpy array of all ones that has 4 rows and 2 columns?

SyntaxError: invalid syntax (<ipython-input-8-0a005ff83740>, line 1)

In [ ]:
zeros_arr = np.zeros((3,4)) # Create a matrix of zeros with 3 rows and 4 columns. 
ones_arr = np.ones((10,20)) # Create a matrix of ones with 10 rows and 20 columns.
identity_arr = np.identity(50) # Create an identity matrix with 50 rows and 50 columns. 
random_arr = np.random.rand(2, 2) # Create a 2x2 array of random floats ranging from 0 to 1. 
range_arr = np.arange(0, 20, 0.5) # Create a numpy array with arguments (start, end, step_size). 

In [6]:
np.linspace(1,10,5)

array([  1.  ,   3.25,   5.5 ,   7.75,  10.  ])

In [ ]:
#indexing? .iloc, .loc, .ix, .ax

In [81]:
range_arr = np.arange(0, 20, 1).reshape(5, 4)
print range_arr
range_arr[1:2,:2] = 0
range_arr

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[ 0,  1,  2,  3],
       [ 0,  0,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [27]:
range_arr[:, 2]

array([ 2,  6, 10, 14, 18])

In [ ]:
range_arr[0:2] 

In [ ]:
range_arr[0:2, 1:3]

In [ ]:
# np ndarray methods

In [28]:
range_arr.sum(axis=0/1)
# mean, std, max, min, argmax, argmin

array([40, 45, 50, 55])

In [88]:
print range_arr
range_arr.argmax(axis=1)

[[ 0  1  2  3]
 [ 0  0  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([3, 3, 3, 3, 3])

In [30]:
range_arr.argmin()#axis=0 

array([0, 0, 0, 0])

In [90]:
range_arr.cumsum(axis=0)
range_arr.cumprod(axis=1)

array([[    0,     0,     0,     0],
       [    0,     0,     0,     0],
       [    8,    72,   720,  7920],
       [   12,   156,  2184, 32760],
       [   16,   272,  4896, 93024]])

In [91]:
my_ndarray = np.array([2, 4, 6, 8, 24, 3, 8, 9, 12])


In [92]:
print np.where(my_ndarray <= 2)
print np.where(my_ndarray == 8)
print np.where(my_ndarray > 6)

(array([0]),)
(array([3, 6]),)
(array([3, 4, 6, 7, 8]),)


In [ ]:
# merge, join, concatentate

In [93]:
import pandas as pd

In [94]:
Schools_df = pd.read_csv("stuff2/Schools.csv")
Players_df = pd.read_csv("stuff2/SchoolsPlayers.csv")

In [95]:
Players_df.head()

playerID   schoolID  yearMin  yearMax
0  aardsda01     pennst     2001     2001
1  aardsda01       rice     2002     2003
2  abbeybe01    vermont     1888     1892
3  abbotgl01  carkansas     1970     1970
4  abbotje01   kentucky     1991     1992

In [98]:
Players_df.playerID.value_counts()
Schools_df.schoolState.value_counts()

PA    57
CA    48
NY    45
TX    41
OH    33
IL    30
NC    30
TN    29
FL    25
VA    25
GA    21
MI    20
IN    19
AL    18
MA    18
MO    16
IA    16
LA    15
SC    15
AR    15
WI    14
CT    13
KS    13
KY    13
WV    12
MD    12
NJ    12
OK    12
WA    11
MS    10
OR    10
MN    10
NE     8
UT     7
CO     7
RI     6
DC     6
ID     5
ME     5
NH     5
VT     4
AZ     4
NM     3
HI     3
DE     2
NV     2
MT     2
WY     1
SD     1
Name: schoolState, dtype: int64

In [97]:
Schools_df.head()

schoolID                       schoolName        schoolCity schoolState  \
0  abilchrist     Abilene Christian University           Abilene          TX   
1     adelphi               Adelphi University       Garden City          NY   
2    adrianmi                   Adrian College            Adrian          MI   
3    airforce  United States Air Force Academy  Colorado Springs          CO   
4       akron              University of Akron             Akron          OH   

  schoolNick  
0   Wildcats  
1   Panthers  
2   Bulldogs  
3    Falcons  
4       Zips

In [107]:
Schools_df.schoolNick.unique()
#Schools_df[Schools_df.schoolState=='MA'].schoolNick.unique()
Schools_df[Schools_df.schoolCity=='Austin'].schoolNick.unique()
#Schools_df.ix[Schools_df.schoolNick=="Lord Jeffs",2]

array(['Tornados', 'Hilltoppers', 'Longhorns'], dtype=object)

In [58]:
Schools_df.shape

(744, 5)

In [108]:
Schools_df = Schools_df.dropna(how='any')
Players_df = Players_df.dropna(how='any')

In [112]:
schoolState_dummies = pd.get_dummies(Schools_df.schoolState, prefix='my_dummy_for').astype(np.int8)
schoolState_dummies.head()

my_dummy_for_AL  my_dummy_for_AR  my_dummy_for_AZ  my_dummy_for_CA  \
0                0                0                0                0   
1                0                0                0                0   
2                0                0                0                0   
3                0                0                0                0   
4                0                0                0                0   

   my_dummy_for_CO  my_dummy_for_CT  my_dummy_for_DC  my_dummy_for_DE  \
0                0                0                0                0   
1                0                0                0                0   
2                0                0                0                0   
3                1                0                0                0   
4                0                0                0                0   

   my_dummy_for_FL  my_dummy_for_GA       ...         my_dummy_for_SD  \
0                0                0       ...                       0   
1                0                0       ...                       0   
2                0                0       ...                       0   
3                0                0       ...                       0   
4                0                0       ...                       0   

   my_dummy_for_TN  my_dummy_for_TX  my_dummy_for_UT  my_dummy_for_VA  \
0                0                1                0                0   
1                0                0                0                0   
2                0                0                0                0   
3                0                0                0                0   
4                0                0                0                0   

   my_dummy_for_VT  my_dummy_for_WA  my_dummy_for_WI  my_dummy_for_WV  \
0                0                0                0                0   
1                0                0                0                0   
2                0                0                0                0   
3                0                0                0                0   
4                0                0                0                0   

   my_dummy_for_WY  
0                0  
1                0  
2                0  
3                0  
4                0  

[5 rows x 49 columns]

In [113]:
Schools_Players_df = Schools_df.join(schoolState_dummies)
Schools_Players_df.head()

schoolID                       schoolName        schoolCity schoolState  \
0  abilchrist     Abilene Christian University           Abilene          TX   
1     adelphi               Adelphi University       Garden City          NY   
2    adrianmi                   Adrian College            Adrian          MI   
3    airforce  United States Air Force Academy  Colorado Springs          CO   
4       akron              University of Akron             Akron          OH   

  schoolNick  my_dummy_for_AL  my_dummy_for_AR  my_dummy_for_AZ  \
0   Wildcats                0                0                0   
1   Panthers                0                0                0   
2   Bulldogs                0                0                0   
3    Falcons                0                0                0   
4       Zips                0                0                0   

   my_dummy_for_CA  my_dummy_for_CO       ...         my_dummy_for_SD  \
0                0                0       ...                       0   
1                0                0       ...                       0   
2                0                0       ...                       0   
3                0                1       ...                       0   
4                0                0       ...                       0   

   my_dummy_for_TN  my_dummy_for_TX  my_dummy_for_UT  my_dummy_for_VA  \
0                0                1                0                0   
1                0                0                0                0   
2                0                0                0                0   
3                0                0                0                0   
4                0                0                0                0   

   my_dummy_for_VT  my_dummy_for_WA  my_dummy_for_WI  my_dummy_for_WV  \
0                0                0                0                0   
1                0                0                0                0   
2                0                0                0                0   
3                0                0                0                0   
4                0                0                0                0   

   my_dummy_for_WY  
0                0  
1                0  
2                0  
3                0  
4                0  

[5 rows x 54 columns]

In [114]:
pd.merge(Schools_df, Players_df, on='schoolID')

schoolID                    schoolName   schoolCity schoolState  \
0     abilchrist  Abilene Christian University      Abilene          TX   
1        adelphi            Adelphi University  Garden City          NY   
2       adrianmi                Adrian College       Adrian          MI   
3       adrianmi                Adrian College       Adrian          MI   
4          akron           University of Akron        Akron          OH   
5          akron           University of Akron        Akron          OH   
6          akron           University of Akron        Akron          OH   
7        alabama         University of Alabama   Tuscaloosa          AL   
8        alabama         University of Alabama   Tuscaloosa          AL   
9        alabama         University of Alabama   Tuscaloosa          AL   
10       alabama         University of Alabama   Tuscaloosa          AL   
11       alabama         University of Alabama   Tuscaloosa          AL   
12       alabama         University of Alabama   Tuscaloosa          AL   
13       alabama         University of Alabama   Tuscaloosa          AL   
14       alabama         University of Alabama   Tuscaloosa          AL   
15       alabama         University of Alabama   Tuscaloosa          AL   
16       alabama         University of Alabama   Tuscaloosa          AL   
17       alabama         University of Alabama   Tuscaloosa          AL   
18       alabama         University of Alabama   Tuscaloosa          AL   
19       alabama         University of Alabama   Tuscaloosa          AL   
20       alabama         University of Alabama   Tuscaloosa          AL   
21       alabama         University of Alabama   Tuscaloosa          AL   
22       alabama         University of Alabama   Tuscaloosa          AL   
23       alabama         University of Alabama   Tuscaloosa          AL   
24       alabama         University of Alabama   Tuscaloosa          AL   
25       alabama         University of Alabama   Tuscaloosa          AL   
26       alabama         University of Alabama   Tuscaloosa          AL   
27       alabama         University of Alabama   Tuscaloosa          AL   
28       alabama         University of Alabama   Tuscaloosa          AL   
29       alabama         University of Alabama   Tuscaloosa          AL   
...          ...                           ...          ...         ...   
6112      xavier             Xavier University   Cincinnati          OH   
6113      xavier             Xavier University   Cincinnati          OH   
6114      xavier             Xavier University   Cincinnati          OH   
6115        yale               Yale University    New Haven          CT   
6116        yale               Yale University    New Haven          CT   
6117        yale               Yale University    New Haven          CT   
6118        yale               Yale University    New Haven          CT   
6119        yale               Yale University    New Haven          CT   
6120        yale               Yale University    New Haven          CT   
6121        yale               Yale University    New Haven          CT   
6122        yale               Yale University    New Haven          CT   
6123        yale               Yale University    New Haven          CT   
6124        yale               Yale University    New Haven          CT   
6125        yale               Yale University    New Haven          CT   
6126        yale               Yale University    New Haven          CT   
6127        yale               Yale University    New Haven          CT   
6128        yale               Yale University    New Haven          CT   
6129        yale               Yale University    New Haven          CT   
6130        yale               Yale University    New Haven          CT   
6131        yale               Yale University    New Haven          CT   
6132        yale               Yale University    New Haven          CT   
6133        yale               Ya

In [80]:
Schools_Players_df = pd.merge(Schools_df, Players_df, on='schoolID')

pd.pivot_table(Schools_Players_df, values='playerID', 
               index='schoolState', columns='schoolNick',
              aggfunc = lambda x: len(x.unique()))

schoolNick   49ers  Aggies  Anchormen  Anteaters  Antelopes  Argonauts  \
schoolState                                                              
AL             NaN     NaN        NaN        NaN        NaN        NaN   
AR             NaN     NaN        NaN        NaN        NaN        NaN   
AZ             NaN     NaN        NaN        NaN       13.0        NaN   
CA            33.0     1.0        NaN        5.0        NaN        NaN   
CO             NaN     NaN        NaN        NaN        NaN        NaN   
CT             NaN     NaN        NaN        NaN        NaN        NaN   
DC             NaN     NaN        NaN        NaN        NaN        NaN   
DE             NaN     NaN        NaN        NaN        NaN        NaN   
FL             NaN     NaN        NaN        NaN        NaN        2.0   
GA             NaN     NaN        NaN        NaN        NaN        NaN   
HI             NaN     NaN        NaN        NaN        NaN        NaN   
IA             NaN     NaN        NaN        NaN        NaN        NaN   
ID             NaN     NaN        NaN        NaN        NaN        NaN   
IL             NaN     NaN        NaN        NaN        NaN        NaN   
IN             NaN     NaN        NaN        NaN        NaN        NaN   
KS             NaN     NaN        NaN        NaN        NaN        NaN   
KY             NaN     NaN        NaN        NaN        NaN        NaN   
LA             NaN     NaN        NaN        NaN        NaN        NaN   
MA             NaN     NaN        NaN        NaN        NaN        NaN   
MD             NaN     NaN        NaN        NaN        NaN        NaN   
ME             NaN     NaN        NaN        NaN        NaN        NaN   
MI             NaN     NaN        NaN        NaN        NaN        NaN   
MN             NaN     NaN        NaN        NaN        NaN        NaN   
MO             NaN     NaN        NaN        NaN        NaN        NaN   
MS             NaN     NaN        NaN        NaN        NaN        NaN   
NC             9.0     2.0        NaN        NaN        NaN        NaN   
NE             NaN     NaN        NaN        NaN        NaN        NaN   
NH             NaN     NaN        NaN        NaN        NaN        NaN   
NJ             NaN     NaN        NaN        NaN        NaN        NaN   
NM             NaN     2.0        NaN        NaN        NaN        NaN   
NV             NaN     NaN        NaN        NaN        NaN        NaN   
NY             NaN     NaN        NaN        NaN        NaN        NaN   
OH             NaN     NaN        NaN        NaN        NaN        NaN   
OK             NaN     2.0        NaN        NaN        NaN        NaN   
OR             NaN     NaN        NaN        NaN        NaN        NaN   
PA             NaN     NaN        NaN        NaN        NaN        NaN   
RI             NaN     NaN        1.0        NaN        NaN        NaN   
SC             NaN     NaN        NaN        NaN        NaN        NaN   
SD             NaN     NaN        NaN        NaN        NaN        NaN   
TN             NaN     NaN        NaN        NaN        NaN        NaN   
TX             NaN    50.0        NaN        NaN        NaN        NaN   
UT             NaN     4.0        NaN        NaN        NaN        NaN   
VA             NaN     NaN        NaN        NaN        NaN        NaN   
VT             NaN     NaN        NaN        NaN        NaN        NaN   
WA             NaN     NaN        NaN        NaN        NaN        NaN   
WI             NaN     NaN        NaN        NaN        NaN        NaN   
WV             NaN     NaN        NaN        NaN        NaN        NaN   
WY             NaN     NaN        NaN        NaN        NaN        NaN   

schoolNick   Auggies  Aztecs  Badgers  Bald Eagles  ...   Waves  Wildcats  \
schoolState                                         ...                     
AL               NaN     NaN      2.0          NaN  ...     NaN       NaN   
AR               NaN     NaN      NaN          NaN  ...     NaN     